//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolitexCompany
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        public int id { get; set; }
        public int client_id { get; set; }
        public int medical_insurance_id { get; set; }
        public System.DateTime date_start { get; set; }
        public System.DateTime date_end { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Medical_insurance Medical_insurance { get; set; }
    }
}
