//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolitexCompany
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MediCarePlusEntities : DbContext
    {
        public static MediCarePlusEntities _context;
        public MediCarePlusEntities()
            : base("name=MediCarePlusEntities")
        {
        }
        public static MediCarePlusEntities GetContext()
        {
            if (_context == null)
                _context = new MediCarePlusEntities();
            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category_insurance> Category_insurance { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Contracts> Contracts { get; set; }
        public virtual DbSet<Medical_insurance> Medical_insurance { get; set; }
        public virtual DbSet<Profit> Profit { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
