//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PolitexCompany
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PolitexCompanyEntities : DbContext
    {
        private static PolitexCompanyEntities _context;
        public PolitexCompanyEntities()
            : base("name=PolitexCompanyEntities")
        {
        }
        public static PolitexCompanyEntities GetContext()
        {
            if (_context == null)
                _context = new PolitexCompanyEntities();

            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coming> Coming { get; set; }
        public virtual DbSet<IncomingMaterials> IncomingMaterials { get; set; }
        public virtual DbSet<Manager> Manager { get; set; }
        public virtual DbSet<Material> Material { get; set; }
        public virtual DbSet<MaterialWarehouse> MaterialWarehouse { get; set; }
        public virtual DbSet<Storekeeper> Storekeeper { get; set; }
        public virtual DbSet<Suppliers> Suppliers { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Warehouse> Warehouse { get; set; }
    }
}
